# Generated by Django 5.2.13 on 2026-05-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional_council',
            field=models.CharField(blank=True, choices=[('COREN', 'COREN'), ('CRM', 'CRM')], max_length=10, verbose_name='Conselho profissional'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_council_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número do conselho profissional'),
        ),
    ]
