# Generated by Django 5.2.13 on 2026-06-21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_professional_council_and_more"),
        ("cases", "0008_casecommunicationmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("notification_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notification_type", models.CharField(default="case_communication_mention", max_length=60)),
                ("title", models.CharField(max_length=160)),
                ("body_preview", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="cases.case")),
                ("communication_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="cases.casecommunicationmessage")),
                ("triggered_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications_triggered", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "read_at", "created_at"], name="accounts_us_recipie_d1fc72_idx"),
                    models.Index(fields=["case", "created_at"], name="accounts_us_case_id_f90c06_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=["recipient", "communication_message"], name="unique_notification_per_recipient_message"),
                ],
            },
        ),
    ]
