# Generated by Django 5.2.13 on 2026-06-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usernotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='accounts_us_recipie_67cc80_idx',
            old_name='accounts_us_recipie_d1fc72_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='accounts_us_case_id_539c73_idx',
            old_name='accounts_us_case_id_f90c06_idx',
        ),
    ]
