# Generated by Django 5.2.13 on 2026-05-05 12:46

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('NEW', 'New'), ('R1_ACK_PROCESSING', 'R1 Ack Processing'), ('EXTRACTING', 'Extracting'), ('LLM_STRUCT', 'LLM Struct'), ('LLM_SUGGEST', 'LLM Suggest'), ('R2_POST_WIDGET', 'R2 Post Widget'), ('WAIT_DOCTOR', 'Wait Doctor'), ('DOCTOR_DENIED', 'Doctor Denied'), ('DOCTOR_ACCEPTED', 'Doctor Accepted'), ('R3_POST_REQUEST', 'R3 Post Request'), ('WAIT_APPT', 'Wait Appointment'), ('APPT_CONFIRMED', 'Appointment Confirmed'), ('APPT_DENIED', 'Appointment Denied'), ('FAILED', 'Failed'), ('R1_FINAL_REPLY_POSTED', 'R1 Final Reply Posted'), ('WAIT_R1_CLEANUP_THUMBS', 'Wait R1 Cleanup'), ('CLEANUP_RUNNING', 'Cleanup Running'), ('CLEANED', 'Cleaned')], default='NEW', max_length=30, protected=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True)),
                ('agency_record_number', models.CharField(blank=True, max_length=20)),
                ('agency_record_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True)),
                ('suggested_action', models.JSONField(blank=True, null=True)),
                ('doctor_decision', models.CharField(blank=True, max_length=10)),
                ('doctor_support_flag', models.CharField(blank=True, default='none', max_length=20)),
                ('doctor_admission_flow', models.CharField(blank=True, max_length=15)),
                ('doctor_reason', models.TextField(blank=True)),
                ('doctor_decided_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_status', models.CharField(blank=True, max_length=15)),
                ('appointment_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_location', models.TextField(blank=True)),
                ('appointment_instructions', models.TextField(blank=True)),
                ('appointment_reason', models.TextField(blank=True)),
                ('appointment_decided_at', models.DateTimeField(blank=True, null=True)),
                ('final_reply_posted_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_decided', to=settings.AUTH_USER_MODEL)),
                ('scheduler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_scheduled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(max_length=10)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['agency_record_number', 'created_at'], name='cases_case_agency__1d35b7_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'timestamp'], name='cases_casee_case_id_012553_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='cases_casee_event_t_1245c7_idx'),
        ),
    ]
