# Generated by Django 5.2.13 on 2026-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('patients_received', models.PositiveIntegerField(default=0)),
                ('reports_processed', models.PositiveIntegerField(default=0)),
                ('cases_evaluated', models.PositiveIntegerField(default=0)),
                ('accepted_scheduled', models.PositiveIntegerField(default=0)),
                ('immediate_admission', models.PositiveIntegerField(default=0)),
                ('refused', models.PositiveIntegerField(default=0)),
                ('in_progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-window_end'],
                'unique_together': {('window_start', 'window_end')},
            },
        ),
    ]
