# Generated by Django 5.2.13 on 2026-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_supervisor_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='doctor_observation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
