# Generated by Django 5.2.13 on 2026-05-31 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_doctor_observation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lock_context',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='lock_role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='case',
            name='lock_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'locked_until'], name='cases_case_status_9206d0_idx'),
        ),
    ]
