# Generated by Django 5.2.13 on 2026-06-04 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_lock_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='post_schedule_issue_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='post_schedule_issue_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='post_schedule_issue_opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_schedule_issues_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='post_schedule_issue_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='post_schedule_issue_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='post_schedule_issue_responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_schedule_issues_responded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='post_schedule_issue_response_action',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='case',
            name='post_schedule_issue_response_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='post_schedule_issue_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
