# Generated by Django 5.2.13 on 2026-06-20 13:32

import apps.cases.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_post_schedule_issue_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('attachment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.cases.models.case_attachment_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_suppressed', models.BooleanField(db_index=True, default=False)),
                ('suppressed_at', models.DateTimeField(blank=True, null=True)),
                ('suppression_reason', models.TextField(blank=True)),
                ('upload_phase', models.CharField(default='initial', max_length=20)),
                ('uploaded_when_case_status', models.CharField(blank=True, max_length=30)),
                ('note', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case')),
                ('suppressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_attachments_suppressed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'created_at'], name='cases_casea_case_id_f4b8ea_idx')],
            },
        ),
    ]
