# Generated by Django 5.2.13 on 2026-06-21 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_add_correction_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCommunicationMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_role', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_communication_messages', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_messages', to='cases.case')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='cases_casec_case_id_44d48d_idx')],
            },
        ),
    ]
