# Generated by Django 5.2.13 on 2026-06-21 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_casecommunicationmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casecommunicationmessage',
            name='message_type',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='casecommunicationmessage',
            name='source_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_notice', to='cases.caseevent'),
        ),
        migrations.AddField(
            model_name='casecommunicationmessage',
            name='system_event_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='casecommunicationmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_communication_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casecommunicationmessage',
            name='author_role',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
