# Generated by Django 5.2.13 on 2026-06-21 23:11

import re

from django.db import migrations, models


_DAYS_ON_SCREEN_PATTERN = re.compile(
    r"\bDias\s+em\s+tela\s*:\s*(\d+)\b",
    flags=re.IGNORECASE,
)


def _extract_max_days(text: str) -> int | None:
    """Extrai o maior valor "Dias em tela: N" do texto."""
    matches = [int(value) for value in _DAYS_ON_SCREEN_PATTERN.findall(text or "")]
    return max(matches) if matches else None


def backfill_regulation_days_on_screen(apps, schema_editor) -> None:
    """Preenche regulation_days_on_screen para casos existentes com extracted_text."""
    Case = apps.get_model("cases", "Case")
    db_alias = schema_editor.connection.alias

    cases = Case.objects.using(db_alias).filter(
        extracted_text__isnull=False,
        regulation_days_on_screen__isnull=True,
    ).exclude(extracted_text__exact="").only("case_id", "extracted_text")

    for case in cases.iterator(chunk_size=500):
        days = _extract_max_days(case.extracted_text)
        if days is not None:
            Case.objects.using(db_alias).filter(case_id=case.case_id).update(
                regulation_days_on_screen=days,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_system_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='regulation_days_on_screen',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            backfill_regulation_days_on_screen,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
