# Generated by Django 5.2.13 on 2026-07-18 18:50

import uuid

from django.db import migrations, models


def backfill_active_post_acceptance_issues(apps, schema_editor):
    """Preenche contexto 'scheduled' e UUID para intercorrências legadas ativas.

    Apenas casos com post_schedule_issue_status in ('opened', 'responded')
    recebem backfill. Casos sem issue ativa permanecem com valores default.

    Cada caso recebe UUID único via uuid.uuid4() individual por instância.
    bulk_update() em lotes para evitar memory pressure.
    """
    Case = apps.get_model("cases", "Case")
    qs = Case.objects.filter(post_schedule_issue_status__in=("opened", "responded"))

    batch_size = 500
    updated: list = []
    for case in qs.iterator(chunk_size=batch_size):
        changed = False
        if not case.post_acceptance_issue_context:
            case.post_acceptance_issue_context = "scheduled"
            changed = True
        if case.post_acceptance_issue_cycle_id is None:
            case.post_acceptance_issue_cycle_id = uuid.uuid4()
            changed = True
        if changed:
            updated.append(case)
        if len(updated) >= batch_size:
            Case.objects.bulk_update(
                updated,
                ["post_acceptance_issue_context", "post_acceptance_issue_cycle_id"],
            )
            updated = []

    if updated:
        Case.objects.bulk_update(
            updated,
            ["post_acceptance_issue_context", "post_acceptance_issue_cycle_id"],
        )


def reverse_backfill(apps, schema_editor):
    """Reverte apenas os campos novos — sem apagar dados legados."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_dashboard_case_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="post_acceptance_issue_context",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="case",
            name="post_acceptance_issue_cycle_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=backfill_active_post_acceptance_issues,
            reverse_code=reverse_backfill,
            elidable=True,
        ),
    ]
