# Generated by Django 5.2.13 on 2026-07-18 18:50

import uuid

from django.db import migrations, models


def backfill_active_post_acceptance_issues(apps, schema_editor):
    """Preenche contexto 'scheduled' e UUID para intercorrências legadas ativas.

    Apenas casos com post_schedule_issue_status in ('opened', 'responded')
    recebem backfill. Casos sem issue ativa permanecem com valores default.
    """
    Case = apps.get_model("cases", "Case")
    qs = Case.objects.filter(post_schedule_issue_status__in=("opened", "responded"))
    # Bulk update em lotes para evitar memory pressure
    batch_size = 500
    pk_list = list(qs.values_list("pk", flat=True))
    for i in range(0, len(pk_list), batch_size):
        batch_pks = pk_list[i : i + batch_size]
        Case.objects.filter(pk__in=batch_pks).update(
            post_acceptance_issue_context="scheduled",
            post_acceptance_issue_cycle_id=uuid.uuid4(),
        )


def reverse_backfill(apps, schema_editor):
    """Reverte apenas os campos novos — sem apagar dados legados."""
    # Os campos serão removidos pela reversão do AddField.
    # Nenhuma ação necessária aqui.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_dashboard_case_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="post_acceptance_issue_context",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="case",
            name="post_acceptance_issue_cycle_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=backfill_active_post_acceptance_issues,
            reverse_code=reverse_backfill,
            elidable=True,
        ),
    ]
