# Generated by Django 5.2.13 on 2026-09-05 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_remove_case_exam_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('patient_admitted', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='cases.case')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed', models.BooleanField(default=False)),
                ('non_performance_reason', models.CharField(blank=True, choices=[('absenteeism', 'Absenteísmo'), ('resource_shortage', 'Cancelamento por falta de recursos no dia'), ('other', 'Outras causas')], max_length=30)),
                ('resource_shortage_detail', models.CharField(blank=True, choices=[('emergency_occupied', 'Urgências que ocuparam o horário'), ('insufficient_time', 'Falta de tempo hábil'), ('equipment_unavailable', 'Equipamento quebrado/não disponível')], max_length=30)),
                ('other_reason', models.TextField(blank=True)),
                ('follow_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_outcomes', to='cases.casefollowup')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_outcomes', to='cases.caseprocedure')),
            ],
        ),
        migrations.AddConstraint(
            model_name='casefollowup',
            constraint=models.UniqueConstraint(fields=('case', 'version'), name='unique_followup_version_per_case'),
        ),
        migrations.AddConstraint(
            model_name='procedurefollowup',
            constraint=models.UniqueConstraint(fields=('follow_up', 'procedure'), name='unique_procedure_per_followup_version'),
        ),
        migrations.AddConstraint(
            model_name='procedurefollowup',
            constraint=models.CheckConstraint(condition=models.Q(('non_performance_reason', ''), ('performed', False), _negated=True), name='followup_reason_required_when_not_performed'),
        ),
        migrations.AddConstraint(
            model_name='procedurefollowup',
            constraint=models.CheckConstraint(condition=models.Q(('performed', False), ('non_performance_reason', ''), _connector='OR'), name='followup_reason_empty_when_performed'),
        ),
        migrations.AddConstraint(
            model_name='procedurefollowup',
            constraint=models.CheckConstraint(condition=models.Q(('non_performance_reason', 'resource_shortage'), ('resource_shortage_detail', ''), _negated=True), name='followup_detail_required_when_resource_shortage'),
        ),
        migrations.AddConstraint(
            model_name='procedurefollowup',
            constraint=models.CheckConstraint(condition=models.Q(('non_performance_reason', 'resource_shortage'), ('resource_shortage_detail', ''), _connector='OR'), name='followup_detail_empty_without_resource_shortage'),
        ),
        migrations.AddConstraint(
            model_name='procedurefollowup',
            constraint=models.CheckConstraint(condition=models.Q(('non_performance_reason', 'other'), ('other_reason', ''), _negated=True), name='followup_other_text_required'),
        ),
        migrations.AddConstraint(
            model_name='procedurefollowup',
            constraint=models.CheckConstraint(condition=models.Q(('non_performance_reason', 'other'), ('other_reason', ''), _connector='OR'), name='followup_other_text_only_for_other'),
        ),
    ]
