# Generated by Django 5.2.13 on 2026-09-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_casefollowup_procedurefollowup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurefollowup',
            name='non_performance_reason',
            field=models.CharField(blank=True, choices=[('absenteeism', 'Absenteísmo'), ('inadequate_prep', 'Preparo inadequado'), ('resource_shortage', 'Cancelamento por falta de recursos no dia'), ('other', 'Outras causas')], max_length=30),
        ),
    ]
