# Generated by Django 5.2.13 on 2026-09-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0018_alter_procedurefollowup_non_performance_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseprocedure",
            name="procedure_type",
            field=models.CharField(
                choices=[
                    ("eda", "EDA"),
                    ("colonoscopy", "Colonoscopia"),
                    ("echoendoscopy", "Ecoendoscopia"),
                    ("cpre", "CPRE"),
                ],
                max_length=20,
            ),
        ),
    ]
