# Generated by Django 5.2.13 on 2026-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_alter_caseprocedure_procedure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurefollowup',
            name='non_performance_reason',
            field=models.CharField(blank=True, choices=[('missing_exam_consent', 'Ausência do preenchimento do TCLE para realização de exame'), ('missing_anesthesia_consent', 'Ausência do preenchimento do TCLE anestésico'), ('clinical_conditions', 'Condições clínicas desfavoráveis'), ('scheduling_error', 'Erro na programação do procedimento'), ('missing_gastroenterologist', 'Falta de médico gastroenterologista'), ('missing_anesthesiologist', 'Falta de anestesiologista'), ('missing_equipment', 'Falta de equipamentos'), ('missing_tests', 'Falta de exames'), ('missing_blood_products', 'Falta de hemoderivados'), ('fasting_not_observed', 'Falta de jejum'), ('missing_material_opme', 'Falta de material/OPME'), ('missing_icu_bed', 'Falta de vaga na UTI'), ('inadequate_prep', 'Preparo inadequado'), ('difficult_intubation', 'Intubação difícil'), ('medical_plan_changed', 'Mudança de conduta médica'), ('patient_no_show', 'Não comparecimento do paciente'), ('patient_death', 'Paciente foi a óbito'), ('emergency_priority', 'Prioridade para urgência'), ('time_exceeded', 'Tempo excedido'), ('transferred_other_hospital', 'Transferência para outro hospital'), ('patient_delay', 'Atraso do paciente'), ('divergent_report', 'Relatório divergente'), ('patient_refusal', 'Recusa do paciente'), ('other', 'Outras causas'), ('absenteeism', 'Absenteísmo'), ('resource_shortage', 'Cancelamento por falta de recursos no dia')], max_length=30),
        ),
    ]
