# Generated by Django 5.2.13 on 2026-09-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0020_alter_procedurefollowup_non_performance_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseprocedure",
            name="procedure_type",
            field=models.CharField(
                choices=[
                    ("eda", "EDA"),
                    ("eda_gastrostomy", "EDA + Gastrostomia (GTT)"),
                    ("eda_capsule", "EDA + Cápsula"),
                    ("eda_dilation", "EDA + Dilatação"),
                    ("colonoscopy", "Colonoscopia"),
                    ("rectosigmoidoscopy", "Retossigmoidoscopia"),
                    ("rectosigmoidoscopy_dilation", "Retossigmoidoscopia + Dilatação"),
                    ("rectosigmoidoscopy_argon", "Retossigmoidoscopia + Argônio"),
                    ("echoendoscopy", "Ecoendoscopia"),
                    ("cpre", "CPRE"),
                ],
                max_length=32,
            ),
        ),
    ]
